### ISSUE TITLE
Error when not using --url

### ISSUE THREAD

**Issue by wildeyes** [horiuchi/dtsgenerator#220]
Using the --url flag to fetch the JSON, the cli works. Specifying a local file, does not.
```
$ DEBUG=dtsgen dtsgen res.json --out types.d.ts
  dtsgen parse schema: schemaId=[undefined], url=[undefined]. +0ms
  dtsgen generate d.ts. +4ms
  dtsgen resolve reference: reference schema count=0. +3ms
  dtsgen TypeId list: +1ms
  dtsgen SchemaId list: +0ms
  dtsgen Reference list: +0ms
Error: There is no id in the input schema(s)
    at JsonSchemaParser.createHierarchicalMap (C:\Users\wie\AppData\Roaming\npm\node_modules\dtsgenerator\src\jsonSchemaParser.js:299:23)
    at JsonSchemaParser._callee$ (C:\Users\wie\AppData\Roaming\npm\node_modules\dtsgenerator\src\jsonSchemaParser.js:278:44)
    at tryCatch (C:\Users\wie\AppData\Roaming\npm\node_modules\dtsgenerator\node_modules\regenerator-runtime\runtime.js:64:40)
    at Generator.invoke [as _invoke] (C:\Users\wie\AppData\Roaming\npm\node_modules\dtsgenerator\node_modules\regenerator-runtime\runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\wie\AppData\Roaming\npm\node_modules\dtsgenerator\node_modules\regenerator-runtime\runtime.js:116:21)
    at fulfilled (C:\Users\wie\AppData\Roaming\npm\node_modules\dtsgenerator\src\jsonSchemaParser.js:15:32)
```

**Comment by wildeyes** [comment]
actually, I made a mistake, you can remove this issue.

**Comment by horiuchi** [comment]
np :+1:
