### ISSUE TITLE
A property name cannot contain a "/"

### ISSUE THREAD

**Issue by Reggino** [horiuchi/dtsgenerator#315]
Thanks for this, this is awesome.

I do run into the following issue. The following (swagger/open api) schema crashes dtsgenerator:

```
{
  "swagger": "2.0",
  "definitions": {
    "Zipcode": {
      "type": "object",
      "properties": {
        "odd/even": {
          "type": "string",
          "enum": [
            "odd",
            "even"
          ]
        }
      }
    }
  }
}

```
Cmd:  dtsgen test.json
Expected result: typescript definitions
Actual result: Error with stacktrace:

```
$ dtsgen test.json 
TypeError: Cannot read property 'id' of undefined
    at getId (/usr/lib/node_modules/dtsgenerator/dist/core/jsonSchema.js:45:19)
    at Object.getSubSchema (/usr/lib/node_modules/dtsgenerator/dist/core/jsonSchema.js:24:21)
    at DtsGenerator.normalizeContent (/usr/lib/node_modules/dtsgenerator/dist/core/dtsGenerator.js:79:35)
    at DtsGenerator.generateProperties (/usr/lib/node_modules/dtsgenerator/dist/core/dtsGenerator.js:152:39)
    at DtsGenerator.generateTypeModel (/usr/lib/node_modules/dtsgenerator/dist/core/dtsGenerator.js:128:14)
    at DtsGenerator.walkSchema (/usr/lib/node_modules/dtsgenerator/dist/core/dtsGenerator.js:69:29)
    at DtsGenerator.walk (/usr/lib/node_modules/dtsgenerator/dist/core/dtsGenerator.js:43:26)
    at DtsGenerator.walk (/usr/lib/node_modules/dtsgenerator/dist/core/dtsGenerator.js:48:26)
    at DtsGenerator.<anonymous> (/usr/lib/node_modules/dtsgenerator/dist/core/dtsGenerator.js:26:30)
    at step (/usr/lib/node_modules/dtsgenerator/node_modules/tslib/tslib.js:133:27)

```

**Comment by horiuchi** [comment]
@Reggino Thank you for your bug report!
I will fix this issue.

**Comment by horiuchi** [comment]
Released the fixed version on `npm`. 👍

**Comment by Reggino** [comment]
That's fast. Awesome, thanks!
