### ISSUE TITLE
Error: id not found

### ISSUE THREAD

**Issue by ianks** [horiuchi/dtsgenerator#33]
Testing against the JSONAPI schema, I received the bug below against version 0.4.0.

To recreate, run this command: `curl jsonapi.org/schema | dtsgen`

```
{ '$schema': 'http://json-schema.org/draft-04/schema#',
  title: 'JSON API Schema',
  description: 'This is a schema for responses in the JSON API format. For more, see http://jsonapi.org',
  oneOf: 
   [ { '$ref': '#/definitions/success' },
     { '$ref': '#/definitions/failure' },
     { '$ref': '#/definitions/info' } ],
  definitions: 
   { success: 
      { type: 'object',
        required: [Object],
        properties: [Object],
        additionalProperties: false },
     failure: 
      { type: 'object',
        required: [Object],
        properties: [Object],
        additionalProperties: false },
     info: 
      { type: 'object',
        required: [Object],
        properties: [Object],
        additionalProperties: false },
     meta: 
      { description: 'Non-standard meta-information that can not be represented as an attribute or relationship.',
        type: 'object',
        additionalProperties: true },
     data: 
      { description: 'The document\'s "primary data" is a representation of the resource or collection of resources targeted by a request.',
        oneOf: [Object] },
     resource: 
      { description: '"Resource objects" appear in a JSON API document to represent resources.',
        type: 'object',
        required: [Object],
        properties: [Object],
        additionalProperties: false },
     links: 
      { description: 'A resource object **MAY** contain references to other resource objects ("relationships"). Relationships may be to-one or to-many. Relationships can be specified by including a member in a resource\'s links object.',
        type: 'object',
        properties: [Object],
        additionalProperties: true },
     link: 
      { description: 'A link **MUST** be represented as either: a string containing the link\'s URL or a link object.',
        oneOf: [Object] },
     attributes: 
      { description: 'Members of the attributes object ("attributes") represent information about the resource object in which it\'s defined.',
        type: 'object',
        patternProperties: [Object],
        additionalProperties: false },
     relationships: 
      { description: 'Members of the relationships object ("relationships") represent references from the resource object in which it\'s defined to other resource objects.',
        type: 'object',
        patternProperties: [Object],
        additionalProperties: false },
     relationshipToOne: 
      { description: 'References to other resource objects in a to-one ("relationship"). Relationships can be specified by including a member in a resource\'s links object.',
        anyOf: [Object] },
     relationshipToMany: 
      { description: 'An array of objects each containing "type" and "id" members for to-many relationships.',
        type: 'array',
        items: [Object],
        uniqueItems: true },
     empty: 
      { description: 'Describes an empty to-one relationship.',
        type: 'null' },
     linkage: 
      { description: 'The "type" and "id" to non-empty members.',
        type: 'object',
        required: [Object],
        properties: [Object],
        additionalProperties: false },
     pagination: { type: 'object', properties: [Object] },
     jsonapi: 
      { description: 'An object describing the server\'s implementation',
        type: 'object',
        properties: [Object],
        additionalProperties: false },
     error: 
      { type: 'object',
        properties: [Object],
        additionalProperties: false } } }
/home/ianks/.nvm/versions/node/v5.8.0/lib/node_modules/dtsgenerator/src/generator.js:11
            throw new Error('id is not found.');
            ^

Error: id is not found.
    at new Generator (/home/ianks/.nvm/versions/node/v5.8.0/lib/node_modules/dtsgenerator/src/generator.js:11:19)
    at Function.Generator.add (/home/ianks/.nvm/versions/node/v5.8.0/lib/node_modules/dtsgenerator/src/generator.js:50:17)
    at /home/ianks/.nvm/versions/node/v5.8.0/lib/node_modules/dtsgenerator/src/index.js:12:20
    at Array.forEach (native)
    at dtsgenerator (/home/ianks/.nvm/versions/node/v5.8.0/lib/node_modules/dtsgenerator/src/index.js:11:13)
    at processGenerate (/home/ianks/.nvm/versions/node/v5.8.0/lib/node_modules/dtsgenerator/src/cli.js:62:18)
    at Socket.<anonymous> (/home/ianks/.nvm/versions/node/v5.8.0/lib/node_modules/dtsgenerator/src/cli.js:40:9)
    at emitNone (events.js:85:20)
    at Socket.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
```

**Comment by horiuchi** [comment]
It's a feature of `dtsgenerator`.
`dtsgenerator` is required `id` property of root level for the output type name.

same as #22

**Comment by ianks** [comment]
Ok, so the JSONAPI schema is incorrect?

**Comment by horiuchi** [comment]
No, the JSON API Schema is correct as JSON Schema.
But the `dtsgenerator` need the `id` property of root level for output type name.

**Comment by ianks** [comment]
Is is possible to use another attribute other than ID? Apparently ID is not meant to be used as a string identifier for schemas, which makes me weary of using it to create the output interface name.

https://github.com/json-schema/json-schema/wiki/The-%22id%22-conundrum#is-id-used-today

**Comment by horiuchi** [comment]
Thank you for suggestion the helpful articles. That wiki is so interesting. 👍
I'm sure that the `id` property has some problem. But I could not find the other property to use as identifier in the JSON Schema draft v4.
Also I think the `baseUri` property in draft v5 is so useful.

**Comment by ianks** [comment]
Maybe we could allow the option to pass in a `--interface-name` argument to the CLI, which could be used if there is no `id` in the schema. Thoughts?
