### ISSUE TITLE
Error: There is no schema in the input contents

### ISSUE THREAD

**Issue by ulivz** [horiuchi/dtsgenerator#394]
# Reproduction

- create a `schema.json`

```json
{
  "id": "http://json-schema.org/geo",
  "$schema": "http://json-schema.org/draft-06/schema#",
  "description": "A geographical coordinate",
  "type": "object",
  "properties": {
    "latitude": {
      "type": "number"
    },
    "longitude": {
      "type": "number"
    }
  }
}
```

- run:

```
dtsgen schema.json
```

- I got this error:

```json
Error: There is no schema in the input contents.
    at SchemaConvertor.buildSchemaMergedMap (/Users/ulivz/Documents/ulivz/dtsgenerator-demo/node_modules/_dtsgenerator@2.4.1@dtsgenerator/dist/core/schemaConvertor.js:66:19)
    at DtsGenerator.<anonymous> (/Users/ulivz/Documents/ulivz/dtsgenerator-demo/node_modules/_dtsgenerator@2.4.1@dtsgenerator/dist/core/dtsGenerator.js:25:46)
    at step (/Users/ulivz/Documents/ulivz/dtsgenerator-demo/node_modules/_tslib@1.10.0@tslib/tslib.js:136:27)
    at Object.next (/Users/ulivz/Documents/ulivz/dtsgenerator-demo/node_modules/_tslib@1.10.0@tslib/tslib.js:117:57)
    at fulfilled (/Users/ulivz/Documents/ulivz/dtsgenerator-demo/node_modules/_tslib@1.10.0@tslib/tslib.js:107:62)
```

**Comment by horiuchi** [comment]
@ulivz Sorry for the late response.

The input JSON is invalid in this case.
If do you use the draft-06 version of JSON Schema, it must use the `$id` property instead of `id`.
If the schema is the draft-04 version, the `id` property is correct.
