### ISSUE TITLE
Single-Quote Plugin & TypeScript v4.1 -- TypeError: Cannot read property 'updateSpreadAssignment' of undefined

### ISSUE THREAD

**Issue by denver-HJS** [horiuchi/dtsgenerator#454]
**Versions:**
`dtsgenerator`: 3.3.1
`@dtsgenerator/single-quote`: 1.4.2
`typescript`: 4.1.2

**Expected Behavior:**
I should be able to generate TS models from an OAS3 file

**Actual Behavior:**
A TypeError is produced:
```
TypeError: Cannot read property 'updateSpreadAssignment' of undefined
    at Object.visitEachChild (/Users/johndoe/workspace/projects/my-service/node_modules/typescript/lib/typescript.js:80801:32)
    at visit (/Users/johndoe/workspace/projects/my-service/node_modules/@dtsgenerator/single-quote/index.js:20:53)
    at Object.visitNode (/Users/johndoe/workspace/projects/my-service/node_modules/typescript/lib/typescript.js:80327:23)
    at /Users/johndoe/workspace/projects/my-service/node_modules/@dtsgenerator/single-quote/index.js:28:49
    at transformation (/Users/johndoe/workspace/projects/my-service/node_modules/dtsgenerator/node_modules/typescript/lib/typescript.js:94097:24)
    at Object.map (/Users/johndoe/workspace/projects/my-service/node_modules/dtsgenerator/node_modules/typescript/lib/typescript.js:551:29)
    at Object.transformNodes (/Users/johndoe/workspace/projects/my-service/node_modules/dtsgenerator/node_modules/typescript/lib/typescript.js:94104:30)
    at Object.transform (/Users/johndoe/workspace/projects/my-service/node_modules/dtsgenerator/node_modules/typescript/lib/typescript.js:140789:25)
    at DtsGenerator.<anonymous> (/Users/johndoe/workspace/projects/my-service/node_modules/dtsgenerator/dist/core/dtsGenerator.js:58:55)
    at step (/Users/johndoe/workspace/projects/my-service/node_modules/tslib/tslib.js:140:27)
```

**Steps to reproduce**:
Run the generator on this minimal OAS3 file
```
{
  "openapi": "3.0.0",
  "info": {
    "title": "Temporary API",
    "version": "1.0.0"
  },
  "paths": {},
  "components": {
    "schemas": {
      "contact": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "phoneNumber": {
            "type": "number"
          }
        }
      }
    }
  }
}
```

**Comment by horiuchi** [comment]
Please retry on the new version.

**Comment by horiuchi** [comment]
If you still have problems, please reopen it.
