### ISSUE TITLE
TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by Goldziher** [horiuchi/dtsgenerator#457]
Hi there,

Thanks for this library, its very useful!

I have been using the library for a long while without issue. I am not sure what changed, I suspect its some typescript compatibility issue - i am using valid openapi specs (validated with swagger-cli), which used to work with this library. The error:

`
TypeError: Cannot read property 'replace' of null
    at escapeString (/Users/nhirschfeld/.nvm/versions/node/v15.2.0/lib/node_modules/dtsgenerator/node_modules/typescript/lib/typescript.js:16266:18)
    at escapeNonAsciiString (/Users/nhirschfeld/.nvm/versions/node/v15.2.0/lib/node_modules/dtsgenerator/node_modules/typescript/lib/typescript.js:16271:13)
    at Object.getLiteralText (/Users/nhirschfeld/.nvm/versions/node/v15.2.0/lib/node_modules/dtsgenerator/node_modules/typescript/lib/typescript.js:13486:34)
    at getLiteralTextOfNode (/Users/nhirschfeld/.nvm/versions/node/v15.2.0/lib/node_modules/dtsgenerator/node_modules/typescript/lib/typescript.js:98322:23)
    at emitLiteral (/Users/nhirschfeld/.nvm/versions/node/v15.2.0/lib/node_modules/dtsgenerator/node_modules/typescript/lib/typescript.js:95932:24)
    at pipelineEmitWithHint (/Users/nhirschfeld/.nvm/versions/node/v15.2.0/lib/node_modules/dtsgenerator/node_modules/typescript/lib/typescript.js:95744:32)
    at pipelineEmitWithComments (/Users/nhirschfeld/.nvm/versions/node/v15.2.0/lib/node_modules/dtsgenerator/node_modules/typescript/lib/typescript.js:98730:17)
    at pipelineEmit (/Users/nhirschfeld/.nvm/versions/node/v15.2.0/lib/node_modules/dtsgenerator/node_modules/typescript/lib/typescript.js:95382:13)
    at emitExpression (/Users/nhirschfeld/.nvm/versions/node/v15.2.0/lib/node_modules/dtsgenerator/node_modules/typescript/lib/typescript.js:95367:20)
    at emitLiteralType (/Users/nhirschfeld/.nvm/versions/node/v15.2.0/lib/node_modules/dtsgenerator/node_modules/typescript/lib/typescript.js:96310:13)
`

I am using typescript 4.12 with the latest version of dtsgenerator. I am afraid I cannot provide the api specs.

**Comment by Goldziher** [comment]
Ok, I debugged the issue in some depth. It seems its caused by my spec contains the following under components.schemas:
`
    NullEnum:
      enum:
        - null
`
